#!/bin/bash

idx=0

mkdir -p ./results_test_app/nonaggr/
mkdir -p ./results_test_app/aggr/

if [ "$1" == "-g" ]; then
    g=$2
else
    echo "give grabmem value"
    exit 1
fi

s=350

if [ "$3" == "-a" ]; then
	while [ $idx -lt 9 ];
	do
	      idx=$((idx + 1))
	      ./test_app -s $s -g $g -i 10 > ./results_test_app/aggr/test_app.s${s}.g${g}.${idx}.out
	done
else
	while [ $idx -lt 9 ];
	do
	      idx=$((idx + 1))
	      ./test_app -s $s -g $g -i 10 -a 0 > ./results_test_app/nonaggr/test_app.s${s}.g${g}.${idx}.out
	done
fi
